#Enter your twitch username and oauth-key below, and the app connects to twitch with the details.
#Your oauth-key can be generated at http://twitchapps.com/tmi/
{
  "twitch": {
    "login": {
      "username": "", 
      "key": "", 
      "channel": "", 
      "clientID": ""
    }, 
    "admins": [
    ],
    "bot":{
      "reconnectionPeriod": 300 # How long the bot will wait without seeing input before trying to reconnect
    }
  },
  "emulator":{
    "inputsFile": "InputKeys.yaml", # Name of file containing commands that the game will use
    "windowName": "" # title of the emulator window
    "repeatDelay": 0.05
  }
}